site_name: Boundary API CLI
theme: readthedocs
pages:
- [index.md, Home]
- ['reference/install.md','Getting Started','Install']
- ['reference/configuration.md','Getting Started','Configuring']
- ['reference/examples.md','Using','Examples']
- ['reference/actions.md','Reference','Actions']
- ['reference/alarms.md','Reference','Alarms']
- ['reference/hostgroups.md','Reference','Host Groups']
- ['reference/measurements.md','Reference','Measurements']
- ['reference/metrics.md','Reference','Metrics']
- ['reference/plugins.md','Reference','Plugins']
- ['reference/sources.md','Reference','Sources']

