site_name: Boundary API CLI
theme: mkdocs
google_analytics: ['UA-63924130-1','http://boundary.github.io/boundary-api-cli/']
pages:
- ['index.md', 'Home']
- ['install.md','Getting Started','Installing']
- ['configuration.md','Getting Started','Configuring']
- ['examples.md','Using','Examples']
- ['reference/actions.md','Reference','Actions']
- ['reference/alarms.md','Reference','Alarms']
- ['reference/hostgroups.md','Reference','Host Groups']
- ['reference/measurements.md','Reference','Measurements']
- ['reference/metrics.md','Reference','Metrics']
- ['reference/plugins.md','Reference','Plugins']
- ['reference/sources.md','Reference','Sources']

